[env]
#LIBCLANG_PATH = { value = "A:\\programFiles\\LLVM\\bin" }
#FFMPEG_DIR = { value = "D:\\flutter_pro\\ffmpeg-4.3\\ffmpeg_install"}

#[source.crates-io]
#replace-with = 'ustc'
#[source.ustc]
#registry = "https://mirrors.ustc.edu.cn/crates.io-index"
#[registries.crates-io]
#protocol = "sparse"
#index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"